spring.application.name=ktpapi
spring.datasource.url=jdbc:mysql://localhost:3306/spring
spring.datasource.username=root
spring.datasource.password=Ridhanovita

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true